###############################################################################
# server properties
###############################################################################


spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:file:./rasperry_sensor_db  # http://localhost:8080/h2-console/login.jsp
    username: sa
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
